name: Prod deploy

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Build and push image
        run: |
          docker build . --tag api-test
          docker push ghcr.io/beingflo/api-test:latest
